name: CI/CD Pipeline for FastAPI App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout App Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}

    - name: Checkout Manifests Repository
      uses: actions/checkout@v3
      with:
        # IMPORTANTE: Troque pelo seu usuário do GitHub aqui
        repository: laissansara/hello-manifests
        path: hello-manifests
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update Image Tag in Manifests
      run: |
        cd hello-manifests
        sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}|' deployment.yaml

    - name: Commit and Push Manifest Changes
      run: |
        cd hello-manifests
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -am "Update image to ${{ github.sha }}"
        git push